### ISSUE TITLE
Missing Spell: Maddening Darkness

### ISSUE THREAD

**Issue by Tyloris** [Frogvall/wc5e-cr-calculator#11]
Like the title says, maddening darkness does not appear in the spell list.

**Comment by Frogvall** [comment]
Spell added. Keep in mind that it suffers from the fact that the calculator don't take DoT into account. Especially since it doesn't even require concentration.

**Comment by Frogvall** [comment]
For the record, DoTs are supported since 24th of Mars 2022.
