### ISSUE TITLE
Arcane Explosion

### ISSUE THREAD

**Issue by Tyloris** [Frogvall/wc5e-cr-calculator#3]
Arcane Explosion is listed as a 5th level spell in the calculator. It's 3rd level in the mage document; must have been changed.

**Comment by Frogvall** [comment]
This means we need to go through the MoM and check if Arcane Explosion is used somewhere and affects the CR.

**Comment by Frogvall** [comment]
Level has not changed. The error is using a comma instead of a dot for the decimal separator, which makes 5 the next argument (spell slot) instead of 3 (and 3 is coincidently translated to "true" and true is ignored).

```js
map.set('Arcane Explosion', new Spell(27.5, 4,5, 3, true));
                                             ^
```
